INSERT INTO products (id, name, price, stock, url, product_category) VALUES (1, '하얀고양이 지팡이', 50000, 10, null, 'MAGIC_WAND');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (2, '치즈고양이 지팡이', 35000, 5, null, 'MAGIC_WAND');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (3, '까만고양이 지팡이', 40000, 20, null, 'MAGIC_WAND');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (4, '4K 수정구', 5000, 20, null, 'CRYSTAL_BALL');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (5, '8K 수정구', 10000, 20, null, 'CRYSTAL_BALL');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (6, '기초 마법1', 7000, 10, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (7, '기초 마법2', 8500, 10, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (8, '숙련 마법1', 2000, 10, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (9, '숙련 마법2', 8500, 30, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (10, '심화 마법1', 16000, 2, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (11, '심화 마법2', 5000, 10, null, 'BOOK');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (12, '체력 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (13, '코딩 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (14, '사랑 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (15, '숙면 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (16, '식사 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (17, '식사 묘약', 50000, 10, null, 'MEDICINE');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (18, '초보 마법사 빗자루 플랜', 50000, 10, null, 'BROOM_PLAN');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (19, '숙련 마법사 빗자루 플랜', 50000, 10, null, 'BROOM_PLAN');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (20, '튜터님 마법사 빗자루 플랜', 50000, 10, null, 'BROOM_PLAN');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (21, '복실복실 버프 고양이', 50000, 10, null, 'POCKET_CAT');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (22, '잘 자는 버프 고양이', 50000, 10, null, 'POCKET_CAT');
INSERT INTO products (id, name, price, stock, url, product_category) VALUES (23, '내손의 튜터님 버프 고양이', 50000, 10, null, 'POCKET_CAT');